### ISSUE TITLE
Buff menu on-click

### ISSUE THREAD

**Issue by Mattamue** [Mattamue/NWN-Buff-Watcher#5]
Menu on buff click is working. Include sub-buffs: uses items special power, shadow conj?

- [x] location for the menu drop-down -- click in the BuffLabelFrame class
- [x] Can 'destroy' the buff, for example if a summon is un-summoned

- [x] Expand the click-menu
        Maybe have a blank buff create and a right-click dropdown for users to choose sub-menus for sub-spells like -- yes did that
        Have a bunch of if statements to determine what menus are available for what types of buffs? -- yup did
        IE spell buffs get extended option -- this is done
        Sub-buffs like shadow conj and prot evil get their sub-spells -- this is done
        have it destroy the buff and make a call back to itself to create the sub-spell? -- this is done, see #42 for challenges

- [x] Abilities triggered on "use Innate Ability" and have drop-down from there in #23, worked well but starting to bloat the buff labelframe class... is that the best place for it?

- [x] Additional options on casting buffs for metamagic extended spells -- handled in #33

- [x] Extended buffs are not moved up in the order because they're still sorted by buff_birthday... change to set_time somehow even though that's a string? -- fixed in #36

- [x] "uses items special power." drop-down -- calling good per #44, happy with how drop-downs work and what is in now
        if not, see if can tie that into idea for right-click power, would be a huge list of stuff?
        weapon essences
        poisons? I think those are more verbose...
        Alchemist fire... also verbose?
        innate abilities? having the invisibility gift or duergar stuff, or drow darkness? -- handled innate in #23

- [x] Buff drop-downs (although the spell versions have the ", mage armor" so that won't be as squirrely -- handled in #41 mostly
        
        Casting: 
        Protection from Alignment
        Protection from Evil -- Protection from Alignment: Evil comes out as this
        Protection from Good -- Protection from Alignment: Good comes out as this
        
        Magic Circle against Alignment
        Magic Circle against Evil -- Magic Circle against Alignment: Evil comes out as this
        Magic Circle against Good -- Magic Circle against Alignment: Good comes out as this
        
        Polymorph
        Polymorph, Giant Spider
        Polymorph, Troll
        Polymorph, Umber Hulk
        Polymorph, Fey
        Polymorph, Zombie
        
        Shadow Conjuration
        Mage Armor -- Shadow Conjuration: Mage Armor comes out as this***
        Ghostly Visage -- Shadow Conjuration: Ghostly Visage comes out as this***
        Greater Shadow Conjuration, Summon Shadow -- Shadow Conjuration: Summon Shadow comes out as this
        
        Shadow Evocation
        Elemental Shield -- Shadow Evocation: Elemental Shield comes out as this
        
        Greater Shadow Conjuration 
        Stoneskin -- Greater Shadow Conjuration: Stoneskin comes out as this
        Greater Shadow Conjuration, Minor Globe of Invulnerability -- does show that one
        Summon Shadow -- Greater Shadow Conjuration: Summon Shadow comes out as this
        
        Aura Versus Alignment
        Unholy Aura -- Aura Versus Alignment: Good *** damage shields, but you can stack... even with damage shields
        Holy Aura -- Aura Versus Alignment: Evil *** damage shields, but you can stack... even with damage shields
        
        Shapechange
        Shapechange, Red Dragon
        Shapechange, Fire Giant
        Shapechange, Balor
        Shapechange, Death Slaad
        Shapechange, Iron Golem
        
        Scroll:
        
        Protection from Alignment -- how scroll comes out
        
        Magic Circle against Alignment -- how scroll comes out
        
        Polymorph Self -- how Polymorph comes out in scroll
        
        Shadow Conjuration -- how Shadow Conjuration comes out in scroll
        
        Greater Shadow Conjuration -- this is how Shadow Evocation comes out in scroll...
        
        Shades -- this is how Greater Shadow Conjuration comes out in scroll, Stoneskin, MinorGI, and Summon Shadow
        
        Aura Versus Alignment -- cannot scribe?
        
        Shapechange -- shows its sub-menu when cast, not when used from scroll

- [x] Item drop-downs -- handled in #43, just adding Dove's Harp as gresto cooldown for now
         all the bard harps
        dove harp -- make sure it ties into Greater Sanc cooldown
