### ISSUE TITLE
Finish chatlog triggers

### ISSUE THREAD

**Issue by Mattamue** [Mattamue/NWN-Buff-Watcher#6]
Finish all codeable chatlog triggers

- [x] Have edge cases for clarity duration, imp invis having 2 parts

- [x] class ability cooldowns

- [x] Better way to handle this than just having a string for each of these in the code? Yes, built a dict to handle the matches
        Start here: https://forum.nwnarelith.com/viewtopic.php?p=231906#p231906

- [x] class ability cooldowns, handled main bulk per #23 
- [x] class ability from summons, needs its own function? -- handled in #24 
- [x] smite cleanup -- complete in #26 
- [x] turn undead, divine shield, divine might cooldown cleanup, can build off of code from smite -- handled in #28
- [x] other misc like scry, pray -- handled in #29
- [x] knockdown cooldown -- handled in #29
- [x] specialist signature spell cooldown -- handled in #30
- [x] tracking the buffs that come from the abilities, like the duration of spirited charge -- partially done, bg bulls added in #37 completed in #38
- [x] see if the hours/3 caster level for GMW is fucky or if its just 120s/level -- fucky seems to last longer... cannot determine how or why

- [x] add triggers for all items, like the Dust of Disappearance and Dust of Appearance to the "uses" json and handling

- [x] triggers for all* scrolls

- [x] triggers for all* potions

- [x] triggers for all* wands

- [x] do a pass for arelith-specific spells for pot/wand/scroll/spell -- captured a few in #47
        Make it a final pass for double-checking everything

- [x] handle loremaster and make sure not added to the "level 1" caster level stuff...

- [x] duration changes: 

- [x] SF trans for Aura of Vit

- [x] SF Illu for Inivis, also handle for imp invis, circle invis

- [x] tenser transformation duration for specialists, longer duration for their signature ability? -- handled in #32

- [x] true seeing duration for SF div

- [x] all "casts" spells... will be a lot

- [x] handle vendor vs player created options? -- handled in #40
         barkskin vendor CL3 vs player CL12
         zoo potions
         Think those are the main two

- [x] damage shields don't stack, but they do in the watcher -- solve by giving them the same "name" or some other way? -- handled in #46 
        Adding a "damage shield" attribute to the buff labelframe class and adding a new line
        to the json that only gets call for the damage shield buffs -- use that for those duplicates?

- [X] Add scroll and wand details to all those so they're captured by the LM character settings

- [x] haste and mass haste shouldn't stack -- handled in #25 

- [x] Epic spells -- handled in #45
